##
# 123Solar nginx configuration
##
server {
        listen 80;
        listen [::]:80;
        server_name _;
        root /var/www/html;
        index index.php index.htm index.html;

        ##
        # Only allow these request methods
        ##
        if ($request_method !~ ^(GET|HEAD|POST)$ ) {
                return 444;
        }

        ##
        # HTTP Authentication for 123Solar admin panel
        ##
        location /123solar/admin {
                index index.php;
                auth_basic           "Restricted";
                auth_basic_user_file /var/www/html/123solar/config/.htpasswd;
        }

        ##
        # Pass PHP scripts to FastCGI server via PHP-FPM Unix socket
        ##
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php-fpm.sock;
        }

        ##
        # Deny access to .ht* files (.htaccess, .htpasswd, etc)
        ##
        location ~ /\.ht {
                deny all;
        }
}
